import { dbConnect } from "@/services/dbConnection";
import { ToastContainer } from "react-toastify";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect()
  return (
    <html lang="en">
        <body className="relative">
          <div id="modal-root-content" className="absolute"/>
          {children}
          <ToastContainer/>
        </body>
    </html>
  );
}