import { dbConnect } from "@/services/dbConnection";
import { SessionProvider } from "next-auth/react";
import { ToastContainer } from "react-toastify";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect()
  return (
    <html lang="en">
        <body>
          <SessionProvider>    
          {children}
          </SessionProvider>
          <ToastContainer/>
        </body>
    </html>
  );
}