import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/Navbar";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthRootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <Navbar authPage={true}/>
        {children}
        <Footer authpage={true}/>
      </body>
    </html>
  );
}
