import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/Navbar";
import { dbConnect } from "@/services/dbConnection";
import { ToastContainer } from "react-toastify";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function HomeRootLayout({ children }) {
  await dbConnect()
  return (
    <html lang="en">
      <body
      >
        <Navbar/>
        {children}
        <Footer/>
        <ToastContainer/>
      </body>
    </html>
  );
}
